name: Reposilite CI

on:
  push:
    branches: [ master, main, "3.0" ]
  pull_request:
    branches: [ master, main, "3.0" ]

jobs:
  build:
    name: "Build with JDK${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Use both LTS releases and latest one
        jdk: [ 8, 11, 17 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :reposilite-backend:testAll :reposilite-backend:shadowJar
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./reposilite-backend/build/reports/jacoco/reposilite-backend-report.xml
        fail_ci_if_error: false
