name: Snapshot builds

on:
  push:
    branches: [ 'main' ]

jobs:
  publish:
    name: Publish snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch git tags # Required for axion-release-plugin
        run: git fetch --tags --unshallow
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew :reposilite-backend:build :reposilite-backend:shadowJar :reposilite-backend:publish
        env:
          MAVEN_NAME: ${{ secrets.MAVEN_NAME }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
  docker:
    name: Docker nightly build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch git tags # Required for axion-release-plugin
        run: git fetch --tags --unshallow
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dzikoysk/reposilite:nightly